# Generated by Django 6.0.3 on 2026-04-06 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_unique_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutiveShadow',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('executive', models.ForeignKey(help_text='The executive who is being shadowed (primary)', on_delete=django.db.models.deletion.CASCADE, related_name='shadowing', to=settings.AUTH_USER_MODEL)),
                ('shadow', models.ForeignKey(help_text='The shadow executive who gets access', on_delete=django.db.models.deletion.CASCADE, related_name='shadow_of', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'executive_shadows',
                'ordering': ['-assigned_at'],
                'unique_together': {('executive', 'shadow')},
            },
        ),
    ]
