# Generated by Django 6.0.3 on 2026-03-24 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiconfig',
            name='provider',
            field=models.CharField(choices=[('groq', 'Groq (Free - Llama)'), ('gemini', 'Google Gemini (Free)'), ('claude', 'Claude (Anthropic)'), ('openai', 'OpenAI GPT')], default='gemini', max_length=20),
        ),
    ]
