# Generated by Django 6.0.3 on 2026-04-11 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0006_sampleitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='dispatch_notified_at',
            field=models.DateTimeField(blank=True, help_text='When the client was notified about dispatch via email', null=True),
        ),
    ]
