# Generated by Django 6.0.3 on 2026-04-22 09:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0007_add_dispatch_notified'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('doc_type', models.CharField(choices=[('coa', 'Certificate of Analysis'), ('msds', 'Material Safety Data Sheet'), ('other', 'Other')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='sample_documents/%Y/%m/')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='samples.sample')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sample_documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
