# Generated by Django 6.0.3 on 2026-04-29 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0008_add_sample_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='firc_received_at',
            field=models.DateTimeField(blank=True, help_text='FIRC received for paid samples — recorded at Dispatched stage.', null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='payment_received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='sample_type',
            field=models.CharField(choices=[('free', 'Free Sample'), ('paid', 'Paid Sample')], default='free', help_text='Free samples skip the reply/payment stages; paid samples include them and FIRC.', max_length=10),
        ),
        migrations.AlterField(
            model_name='sample',
            name='status',
            field=models.CharField(choices=[('requested', 'Mail Received'), ('replied', 'Reply Sent'), ('prepared', 'Prepared'), ('payment_received', 'Payment Received'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered'), ('feedback_pending', 'Feedback Pending'), ('feedback_received', 'Feedback Received')], default='requested', max_length=30),
        ),
    ]
