# Generated by Django 6.0.3 on 2026-04-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0009_sample_firc_received_at_sample_payment_received_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='sample_type_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_type',
            field=models.CharField(blank=True, choices=[('free', 'Free Sample'), ('paid', 'Paid Sample')], default='', help_text='Free samples skip the reply/payment stages; paid samples include them and FIRC.', max_length=10),
        ),
    ]
