# Generated by Django 6.0.3 on 2026-03-24 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamchat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('file', 'File')], default='text', max_length=10),
        ),
    ]
