# Generated by Django 6.0.3 on 2026-03-23 06:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number_id', models.CharField(max_length=50, unique=True)),
                ('business_account_id', models.CharField(blank=True, max_length=50)),
                ('access_token', models.TextField(default='')),
                ('verify_token', models.CharField(max_length=255)),
                ('webhook_secret', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'whatsapp_configs',
            },
        ),
        migrations.AddField(
            model_name='communication',
            name='email_in_reply_to',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='communication',
            name='email_message_id',
            field=models.CharField(blank=True, db_index=True, max_length=500),
        ),
        migrations.AddField(
            model_name='communication',
            name='external_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='communication',
            name='external_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='communication',
            name='whatsapp_message_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('imap_host', models.CharField(max_length=255)),
                ('imap_port', models.IntegerField(default=993)),
                ('smtp_host', models.CharField(max_length=255)),
                ('smtp_port', models.IntegerField(default=587)),
                ('username', models.CharField(max_length=255)),
                ('password', models.TextField(default='')),
                ('use_ssl', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'email_accounts',
            },
        ),
        migrations.AddField(
            model_name='communication',
            name='email_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications', to='communications.emailaccount'),
        ),
    ]
