# Generated by Django 6.0.3 on 2026-03-23 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('communications', '0002_whatsappconfig_communication_email_in_reply_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communication',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='clients.client'),
        ),
    ]
