# Generated by Django 6.0.3 on 2026-03-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_alter_communication_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='email_cc',
            field=models.TextField(blank=True, default='', help_text='Comma-separated CC emails'),
        ),
    ]
