# Generated by Django 6.0.3 on 2026-03-25 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0004_communication_email_cc'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communication',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='communicationattachment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communicationattachment',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='whatsappconfig',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whatsappconfig',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
