# Generated by Django 6.0.3 on 2026-03-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0006_emaildraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaildraft',
            name='cc',
            field=models.TextField(blank=True, default='', help_text='Comma-separated CC emails'),
        ),
    ]
