# Generated by Django 6.0.3 on 2026-03-28 10:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_phone_number_client_tax_number'),
        ('communications', '0007_emaildraft_cc'),
        ('quotations', '0004_quotation_country_of_final_destination_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('source_channel', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('sender_name', models.CharField(blank=True, max_length=255)),
                ('sender_email', models.EmailField(blank=True, max_length=254)),
                ('sender_phone', models.CharField(blank=True, max_length=50)),
                ('client_auto_created', models.BooleanField(default=False, help_text='True if client was auto-created from this request')),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('converted', 'Converted to Quote'), ('rejected', 'Rejected')], default='new', max_length=20)),
                ('ai_confidence', models.FloatField(default=0, help_text='0-1 confidence score for quote intent detection')),
                ('extracted_product', models.CharField(blank=True, max_length=500)),
                ('extracted_quantity', models.CharField(blank=True, max_length=100)),
                ('extracted_unit', models.CharField(blank=True, default='MT', max_length=50)),
                ('extracted_packaging', models.CharField(blank=True, max_length=255)),
                ('extracted_destination_country', models.CharField(blank=True, max_length=100)),
                ('extracted_destination_port', models.CharField(blank=True, max_length=100)),
                ('extracted_delivery_terms', models.CharField(blank=True, max_length=100)),
                ('extracted_payment_terms', models.CharField(blank=True, max_length=255)),
                ('extracted_notes', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_quote_requests', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quote_requests', to='clients.client')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.contact')),
                ('linked_quotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_requests', to='quotations.quotation')),
                ('source_communication', models.OneToOneField(help_text='The communication that triggered this quote request', on_delete=django.db.models.deletion.CASCADE, related_name='quote_request', to='communications.communication')),
            ],
            options={
                'db_table': 'quote_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
