# Generated by Django 6.0.3 on 2026-04-03 09:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0011_add_archived_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaildraft',
            name='draft_version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='emaildraft',
            name='last_saved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DraftAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('file', models.FileField(upload_to='draft_attachments/%Y/%m/')),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(default=0)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='communications.emaildraft')),
            ],
            options={
                'db_table': 'draft_attachments',
            },
        ),
    ]
