# Generated by Django 6.0.3 on 2026-04-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0012_add_draft_save_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='is_starred',
            field=models.BooleanField(db_index=True, default=False, help_text='Starred/flagged by user'),
        ),
    ]
