# Generated by Django 6.0.3 on 2026-04-16 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0014_protect_user_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaildraft',
            name='editor_data',
            field=models.JSONField(blank=True, default=dict, help_text='Stores COA/MSDS/document editor state so it persists across draft saves'),
        ),
    ]
