# Generated by Django 6.0.3 on 2026-04-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0015_add_editor_data_to_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='email_references',
            field=models.TextField(blank=True, default=''),
        ),
    ]
