# Generated by Django 6.0.3 on 2026-03-25 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='freight_terms',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('direct', 'Direct Order'), ('pi_based', 'PI Based')], default='direct', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_terms',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='po_document',
            field=models.FileField(blank=True, null=True, upload_to='purchase_orders/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='order',
            name='po_number',
            field=models.CharField(blank=True, help_text='Client PO number or signed PI reference', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='po_received_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('pi_sent', 'PI Sent'), ('po_received', 'PO Received'), ('docs_preparing', 'Documents Preparing'), ('docs_approved', 'Documents Approved'), ('factory_ready', 'Factory Ready'), ('container_booked', 'Container Booked'), ('inspection', 'Under Inspection'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20),
        ),
    ]
