# Generated by Django 6.0.3 on 2026-03-26 06:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_deleted_at_order_is_deleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='container_booked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='docs_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='factory_ready_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='inspection_passed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pi_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='po_received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='po_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('pi_sent', 'PI Sent'), ('po_received', 'PO Received'), ('docs_preparing', 'Documents Preparing'), ('docs_approved', 'Documents Approved'), ('factory_ready', 'Factory Ready'), ('container_booked', 'Container Booked'), ('inspection', 'Under Inspection'), ('inspection_passed', 'Inspection Passed'), ('dispatched', 'Dispatched'), ('in_transit', 'In Transit'), ('arrived', 'Arrived at Port'), ('customs', 'Customs Clearance'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='confirmed', max_length=30),
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('to_email', models.EmailField(max_length=254)),
                ('cc', models.TextField(blank=True)),
                ('subject', models.CharField(max_length=500)),
                ('body', models.TextField()),
                ('status', models.CharField(default='sent', max_length=20)),
                ('error', models.TextField(blank=True)),
                ('triggered_by', models.CharField(blank=True, help_text='status_change, manual, etc.', max_length=50)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='orders.order')),
            ],
            options={
                'db_table': 'email_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('doc_type', models.CharField(choices=[('pi', 'Proforma Invoice'), ('po', 'Purchase Order'), ('commercial_invoice', 'Commercial Invoice'), ('packing_list', 'Packing List'), ('bl', 'Bill of Lading'), ('coa', 'Certificate of Analysis'), ('insurance', 'Insurance Certificate'), ('other', 'Other')], max_length=30)),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='order_documents/%Y/%m/')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_documents', to='orders.order')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'order_documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('from_status', models.CharField(max_length=30)),
                ('to_status', models.CharField(max_length=30)),
                ('remarks', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order')),
            ],
            options={
                'db_table': 'order_status_history',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowEventLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('event_type', models.CharField(choices=[('status_change', 'Status Change'), ('email_sent', 'Email Sent'), ('doc_uploaded', 'Document Uploaded'), ('payment_received', 'Payment Received'), ('note', 'Note')], max_length=30)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='orders.order')),
                ('triggered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workflow_event_logs',
                'ordering': ['created_at'],
            },
        ),
    ]
