# Generated by Django 6.0.3 on 2026-04-03 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_pif_sent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('po_received', 'PO Received'), ('pif_sent', 'PIF Sent'), ('docs_preparing', 'Documents Preparing'), ('docs_approved', 'Documents Approved'), ('factory_ready', 'Factory Ready'), ('container_booked', 'Container Booked'), ('inspection', 'Under Inspection'), ('inspection_passed', 'Inspection Passed'), ('dispatched', 'Dispatched'), ('in_transit', 'In Transit'), ('arrived', 'Arrived at Port'), ('customs', 'Customs Clearance'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='confirmed', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(help_text='Company/internal product name', max_length=255),
        ),
    ]
