# Generated by Django 6.0.3 on 2026-04-04 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_add_missing_timestamp_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('po_received', 'PO Received'), ('pif_sent', 'PIF Sent'), ('docs_preparing', 'Documents Preparing'), ('docs_approved', 'Documents Approved'), ('factory_ready', 'Factory Ready'), ('container_booked', 'Container Booked'), ('inspection', 'Under Inspection'), ('inspection_passed', 'Inspection Passed'), ('dispatched', 'Dispatched'), ('in_transit', 'In Transit'), ('arrived', 'Delivered'), ('customs', 'Customs Clearance'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='confirmed', max_length=30),
        ),
    ]
