# Generated by Django 6.0.3 on 2026-04-22 11:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_doc_soft_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('po_received', 'PO Received'), ('pif_sent', 'PIF Sent'), ('docs_preparing', 'Documents Preparing'), ('docs_approved', 'Documents Approved'), ('factory_ready', 'Product Readiness'), ('container_booked', 'Container Booked'), ('inspection', 'Under Inspection'), ('inspection_passed', 'Inspection Passed'), ('dispatched', 'Dispatched'), ('in_transit', 'In Transit'), ('arrived', 'Delivered'), ('customs', 'Customs Clearance'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='confirmed', max_length=30),
        ),
        migrations.CreateModel(
            name='OrderFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('issues', models.TextField(blank=True)),
                ('bulk_order_interest', models.BooleanField(default=False)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='orders.order')),
            ],
            options={
                'db_table': 'order_feedback',
            },
        ),
    ]
