# Generated by Django 6.0.3 on 2026-04-24 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_orderdocument_doc_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdocument',
            name='doc_type',
            field=models.CharField(choices=[('pi', 'Proforma Invoice'), ('pif', 'Packing Instructions Form'), ('po', 'Purchase Order'), ('commercial_invoice', 'Commercial Invoice'), ('packing_list', 'Packing List'), ('bl', 'Bill of Lading'), ('coa', 'Certificate of Analysis'), ('insurance', 'Insurance Certificate'), ('note_attachment', 'Note Attachment'), ('other', 'Other')], max_length=30),
        ),
    ]
