# Generated by Django 6.0.3 on 2026-04-24 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_orderdocument_doc_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='readiness_checklist',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
