# Generated by Django 6.0.3 on 2026-04-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_alter_orderdocument_doc_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdocument',
            name='doc_type',
            field=models.CharField(choices=[('pi', 'Proforma Invoice'), ('pif', 'Packing Instructions Form'), ('po', 'Purchase Order'), ('commercial_invoice', 'Commercial Invoice'), ('packing_list', 'Packing List'), ('bl', 'Bill of Lading'), ('coa', 'Certificate of Analysis'), ('insurance', 'Insurance Certificate'), ('note_attachment', 'Note Attachment'), ('client_invoice', 'Client Invoice'), ('client_packing_list', 'Client Packing List'), ('logistic_invoice', 'Logistic Invoice'), ('logistic_packing_list', 'Logistic Packing List'), ('msds', 'Material Safety Data Sheet'), ('dbk_declaration', 'DBK Declaration'), ('examination_report', 'Examination Report'), ('export_declaration', 'Export Declaration Form'), ('factory_stuffing', 'Factory Stuffing'), ('non_dg_declaration', 'Non-DG Declaration'), ('other', 'Other')], max_length=30),
        ),
    ]
