# Generated by Django 6.0.3 on 2026-04-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_alter_orderdocument_doc_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='last_cro_reminder_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
