# Generated by Django 6.0.3 on 2026-04-25 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_alter_orderdocument_doc_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
