# Generated by Django 6.0.3 on 2026-04-27 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_order_delivery_reminder_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdocument',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='orders.orderitem'),
        ),
    ]
