# Generated by Django 6.0.3 on 2026-04-28 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_orderdocument_order_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='firc_received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
