# Generated by Django 6.0.3 on 2026-05-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_order_source_communication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('po_received', 'PO Received'), ('pif_sent', 'PIF Sent'), ('docs_preparing', 'Documents Preparing'), ('docs_approved', 'Documents Approved'), ('factory_ready', 'Product Readiness'), ('container_booked', 'Container Booked'), ('inspection', 'Under Inspection'), ('inspection_passed', 'Inspection Status'), ('dispatched', 'Dispatched'), ('in_transit', 'In Transit'), ('arrived', 'Delivered'), ('customs', 'Customs Clearance'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='confirmed', max_length=30),
        ),
    ]
