# Generated by Django 6.0.3 on 2026-05-04 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='last_transit_reminder_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
