# Generated by Django 6.0.3 on 2026-03-21 11:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='COADocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coa_type', models.CharField(default='lab', help_text='lab or client', max_length=20)),
                ('file', models.FileField(upload_to='coa/%Y/%m/')),
                ('version', models.IntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coa_documents', to='shipments.shipment')),
            ],
            options={
                'db_table': 'coa_documents',
            },
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspection_date', models.DateField()),
                ('inspector_name', models.CharField(max_length=255)),
                ('inspection_type', models.CharField(choices=[('pre_dispatch', 'Pre-Dispatch'), ('container_loading', 'Container Loading'), ('third_party', 'Third Party')], max_length=30)),
                ('status', models.CharField(choices=[('passed', 'Passed'), ('conditional', 'Conditional'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='shipments.shipment')),
            ],
            options={
                'db_table': 'inspections',
            },
        ),
        migrations.CreateModel(
            name='InspectionMedia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='inspections/%Y/%m/')),
                ('media_type', models.CharField(default='photo', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='quality.inspection')),
            ],
            options={
                'db_table': 'inspection_media',
            },
        ),
    ]
