# Generated by Django 6.0.3 on 2026-04-16 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0002_coadocument_deleted_at_coadocument_is_deleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='COAReportCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.CharField(help_text='YYMM e.g. 2604', max_length=4, unique=True)),
                ('last_sequence', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'coa_report_counters',
            },
        ),
    ]
