# Generated by Django 6.0.3 on 2026-03-25 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='freight_terms',
            field=models.CharField(blank=True, choices=[('sea_fcl', 'Sea - FCL (Full Container Load)'), ('sea_lcl', 'Sea - LCL (Less Container Load)'), ('air', 'Air Freight'), ('courier', 'Courier'), ('ex_works', 'Ex Works (Buyer arranges)')], default='sea_fcl', max_length=20),
        ),
        migrations.AddField(
            model_name='quotation',
            name='payment_terms',
            field=models.CharField(blank=True, choices=[('advance', '100% Advance'), ('50_advance', '50% Advance + 50% Before Shipment'), ('30_70', '30% Advance + 70% Against BL'), ('lc', 'Letter of Credit (LC)'), ('da', 'D/A - Documents Against Acceptance'), ('dp', 'D/P - Documents Against Payment'), ('cad', 'CAD - Cash Against Documents'), ('tt', 'TT - Telegraphic Transfer'), ('credit_30', 'Net 30 Days Credit'), ('credit_60', 'Net 60 Days Credit'), ('custom', 'Custom Terms')], default='advance', max_length=30),
        ),
        migrations.AddField(
            model_name='quotation',
            name='payment_terms_detail',
            field=models.CharField(blank=True, help_text='Custom payment terms if applicable', max_length=255),
        ),
        migrations.AddField(
            model_name='quotation',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='sent_via',
            field=models.CharField(blank=True, help_text='email or whatsapp', max_length=20),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='delivery_terms',
            field=models.CharField(choices=[('EXW', 'EXW - Ex Works (Factory)'), ('FCA', 'FCA - Free Carrier'), ('FOB', 'FOB - Free on Board'), ('CFR', 'CFR - Cost & Freight'), ('CIF', 'CIF - Cost Insurance & Freight'), ('DAP', 'DAP - Delivered at Place'), ('DDP', 'DDP - Delivered Duty Paid')], default='FOB', max_length=20),
        ),
    ]
