# Generated by Django 6.0.3 on 2026-03-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0003_inquiry_deleted_at_inquiry_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='country_of_final_destination',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='quotation',
            name='country_of_origin',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='quotation',
            name='final_destination',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='quotation',
            name='port_of_discharge',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='quotation',
            name='port_of_loading',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='quotation',
            name='vessel_flight_no',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
