# Generated by Django 6.0.3 on 2026-03-30 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0004_quotation_country_of_final_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='display_overrides',
            field=models.JSONField(blank=True, default=dict, help_text='Custom labels, footer text, consignee lines etc. from the editor form'),
        ),
    ]
