# Generated by Django 6.0.3 on 2026-04-10 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0006_quotationitem_client_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationitem',
            name='client_product_name',
            field=models.TextField(blank=True, default='', help_text='Product name as the client calls it'),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='product_name',
            field=models.TextField(help_text='Company/internal product name'),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='unit',
            field=models.TextField(blank=True, default='KG'),
        ),
    ]
