# Generated by Django 6.0.3 on 2026-04-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0007_item_text_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationitem',
            name='client_product_name',
            field=models.CharField(blank=True, default='', help_text='Product name as the client calls it', max_length=255),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='product_name',
            field=models.CharField(help_text='Company/internal product name', max_length=255),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='unit',
            field=models.CharField(default='KG', max_length=20),
        ),
    ]
