# Generated by Django 6.0.3 on 2026-04-28 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0016_communication_email_references'),
        ('quotations', '0008_alter_quotationitem_client_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='source_communication',
            field=models.ForeignKey(blank=True, help_text='Inbound client email this quotation responds to (drives email threading).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='communications.communication'),
        ),
    ]
