# Generated by Django 6.0.3 on 2026-03-25 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hsn_code',
            field=models.CharField(blank=True, help_text='HSN/HS Code', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(default='MT', max_length=20),
        ),
    ]
