# Generated by Django 6.0.3 on 2026-04-03 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_client_brand_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='client_brand_names',
            field=models.TextField(blank=True, default='', help_text='Comma-separated alternate names clients use for this product (e.g. aza, azarate, azadin)'),
        ),
    ]
