# Generated by Django 6.0.3 on 2026-04-13 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_add_price_list_purchase_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdocument',
            name='doc_type',
            field=models.CharField(blank=True, choices=[('coa', 'Certificate of Analysis (COA)'), ('msds', 'Material Safety Data Sheet (MSDS)'), ('tds', 'Technical Data Sheet (TDS)'), ('certificate', 'Certificate'), ('brochure', 'Brochure'), ('regulatory', 'Regulatory Document'), ('technical', 'Technical Document'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
