# Generated by Django 6.0.3 on 2026-05-13 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_doc_type_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quality_spec',
            field=models.JSONField(blank=True, default=dict, help_text='COA spec (components + acceptable max)'),
        ),
    ]
