# Generated by Django 6.0.3 on 2026-03-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllog',
            name='follow_up_actions',
            field=models.TextField(blank=True, help_text='Action items from the meeting'),
        ),
        migrations.AddField(
            model_name='calllog',
            name='meeting_link',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='calllog',
            name='platform',
            field=models.CharField(choices=[('google_meet', 'Google Meet'), ('zoom', 'Zoom'), ('teams', 'Microsoft Teams'), ('whatsapp', 'WhatsApp Video'), ('phone', 'Phone Call'), ('in_person', 'In Person'), ('other', 'Other')], default='google_meet', max_length=20),
        ),
        migrations.AddField(
            model_name='calllog',
            name='recording_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='calllog',
            name='summary',
            field=models.TextField(blank=True, help_text='Meeting summary / key decisions'),
        ),
        migrations.AddField(
            model_name='calllog',
            name='transcription',
            field=models.TextField(blank=True, help_text='Meeting transcription'),
        ),
    ]
