# Generated by Django 6.0.3 on 2026-03-23 10:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_calllog_follow_up_actions_calllog_meeting_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingPlatformConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('zoom', 'Zoom'), ('google', 'Google Meet'), ('teams', 'Microsoft Teams')], max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('zoom_account_id', models.CharField(blank=True, max_length=255)),
                ('zoom_client_id', models.CharField(blank=True, max_length=255)),
                ('zoom_client_secret', models.TextField(blank=True)),
                ('google_credentials_json', models.TextField(blank=True)),
                ('google_calendar_id', models.CharField(blank=True, default='primary', max_length=255)),
                ('teams_tenant_id', models.CharField(blank=True, max_length=255)),
                ('teams_client_id', models.CharField(blank=True, max_length=255)),
                ('teams_client_secret', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'meeting_platform_configs',
            },
        ),
    ]
