# Generated by Django 6.0.3 on 2026-03-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_meetingplatformconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingplatformconfig',
            name='google_credentials_json',
        ),
        migrations.AddField(
            model_name='meetingplatformconfig',
            name='google_client_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='meetingplatformconfig',
            name='google_client_secret',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='meetingplatformconfig',
            name='google_refresh_token',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='meetingplatformconfig',
            name='google_user_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
