# Generated by Django 6.0.3 on 2026-03-25 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_remove_meetingplatformconfig_google_credentials_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllog',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calllog',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='meetingplatformconfig',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meetingplatformconfig',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
