# Generated by Django 6.0.3 on 2026-04-06 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_deleted_at_task_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status_note',
            field=models.CharField(blank=True, help_text='Custom status update text', max_length=500),
        ),
    ]
