# Generated by Django 6.0.3 on 2026-03-27 09:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_phone_number_client_tax_number'),
        ('finance', '0004_proformainvoice_proformainvoiceitem'),
        ('orders', '0004_order_confirmed_at_order_container_booked_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('invoice_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent')], default='draft', max_length=20)),
                ('exporter_ref', models.CharField(blank=True, help_text='Exporter Ref / IEC etc.', max_length=255)),
                ('client_company_name', models.CharField(max_length=255)),
                ('client_tax_number', models.CharField(blank=True, max_length=100)),
                ('client_address', models.TextField(blank=True)),
                ('client_pincode', models.CharField(blank=True, max_length=30)),
                ('client_city_state_country', models.CharField(blank=True, max_length=255)),
                ('client_phone', models.CharField(blank=True, max_length=50)),
                ('notify_company_name', models.CharField(blank=True, max_length=255)),
                ('notify_address', models.TextField(blank=True)),
                ('notify_phone', models.CharField(blank=True, max_length=50)),
                ('buyer_order_no', models.CharField(blank=True, max_length=100)),
                ('buyer_order_date', models.DateField(blank=True, null=True)),
                ('country_of_origin', models.CharField(default='India', max_length=100)),
                ('country_of_final_destination', models.CharField(blank=True, max_length=100)),
                ('port_of_loading', models.CharField(blank=True, max_length=100)),
                ('port_of_discharge', models.CharField(blank=True, max_length=100)),
                ('vessel_flight_no', models.CharField(blank=True, max_length=100)),
                ('final_destination', models.CharField(blank=True, max_length=100)),
                ('pre_carriage_by', models.CharField(blank=True, max_length=100)),
                ('place_of_receipt', models.CharField(blank=True, max_length=100)),
                ('terms_of_delivery', models.CharField(blank=True, help_text='e.g. FOB - Chennai Port', max_length=100)),
                ('payment_terms', models.CharField(blank=True, help_text='e.g. D/A 30 Days', max_length=255)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('total_fob_usd', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('freight', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('insurance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_invoice_usd', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=0, help_text='USD to INR rate', max_digits=10)),
                ('total_fob_inr', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('freight_inr', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('insurance_inr', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_invoice_inr', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('igst_rate', models.DecimalField(decimal_places=2, default=0, help_text='IGST percentage e.g. 18', max_digits=5)),
                ('igst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('grand_total_inr', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('amount_in_words', models.CharField(blank=True, max_length=500)),
                ('bank_details', models.TextField(default='Bank name: ICICI Bank Ltd\nBranch name: Salem Main Branch\nBeneficiary: Kriya Biosys Private Limited\nIFSC Code: ICIC0006119\nSwift Code: ICICINBB')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='commercial_invoices/%Y/%m/')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_invoices', to='clients.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commercial_invoices', to='orders.order')),
            ],
            options={
                'db_table': 'commercial_invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommercialInvoiceItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('hsn_code', models.CharField(blank=True, help_text='HSN/SAC Code', max_length=50)),
                ('packages_description', models.TextField(blank=True, help_text='No. & Kind of Packages')),
                ('description_of_goods', models.TextField(blank=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unit', models.CharField(default='KG', max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.commercialinvoice')),
            ],
            options={
                'db_table': 'commercial_invoice_items',
            },
        ),
    ]
