# Generated by Django 6.0.3 on 2026-03-30 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_commercialinvoice_commercialinvoiceitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='proformainvoice',
            name='display_overrides',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
