# Generated by Django 6.0.3 on 2026-03-30 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_proformainvoice_display_overrides'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialinvoice',
            name='display_overrides',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
