# Generated by Django 6.0.3 on 2026-04-02 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0010_communication_is_read'),
        ('finance', '0008_add_client_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='proformainvoice',
            name='source_communication',
            field=models.ForeignKey(blank=True, help_text='The communication that triggered this PI request', null=True, on_delete=django.db.models.deletion.SET_NULL, to='communications.communication'),
        ),
        migrations.AlterField(
            model_name='commercialinvoiceitem',
            name='product_name',
            field=models.CharField(help_text='Company/internal product name', max_length=255),
        ),
        migrations.AlterField(
            model_name='proformainvoiceitem',
            name='product_name',
            field=models.CharField(help_text='Company/internal product name', max_length=255),
        ),
    ]
