# Generated by Django 6.0.3 on 2026-04-04 05:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_add_price_list_purchase_history'),
        ('finance', '0009_add_pi_source_communication'),
        ('orders', '0009_add_logistics_invoice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogisticsInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('invoice_date', models.DateField()),
                ('exporter_ref', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent')], default='draft', max_length=20)),
                ('client_company_name', models.CharField(max_length=255)),
                ('client_tax_number', models.CharField(blank=True, max_length=100)),
                ('client_address', models.TextField(blank=True)),
                ('client_pincode', models.CharField(blank=True, max_length=30)),
                ('client_city_state_country', models.CharField(blank=True, max_length=255)),
                ('client_phone', models.CharField(blank=True, max_length=50)),
                ('notify_company_name', models.CharField(blank=True, max_length=255)),
                ('notify_address', models.TextField(blank=True)),
                ('notify_phone', models.CharField(blank=True, max_length=50)),
                ('country_of_origin', models.CharField(default='India', max_length=100)),
                ('country_of_final_destination', models.CharField(blank=True, max_length=100)),
                ('port_of_loading', models.CharField(blank=True, max_length=100)),
                ('port_of_discharge', models.CharField(blank=True, max_length=100)),
                ('vessel_flight_no', models.CharField(blank=True, max_length=100)),
                ('final_destination', models.CharField(blank=True, max_length=100)),
                ('terms_of_delivery', models.CharField(blank=True, max_length=100)),
                ('payment_terms', models.CharField(blank=True, max_length=255)),
                ('buyer_reference', models.CharField(blank=True, max_length=100)),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('total_fob_usd', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('freight', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('insurance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('subtotal_usd', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('subtotal_inr', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('igst_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('igst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('grand_total_inr', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('amount_in_words', models.CharField(blank=True, max_length=500)),
                ('shipping_forwarding', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('bank_details', models.TextField(default='Bank name: DBS Bank Ltd\nBranch name: Salem - India\nBeneficiary: Kriya Biosys Private Limited\nIFSC Code: DBSS0IN0811\nSwift Code: DBSSINBB\nA/C No: K32250073646\nA/C Type: CA Account')),
                ('display_overrides', models.JSONField(blank=True, default=dict)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='logistics_invoices/%Y/%m/')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logistics_invoices', to='clients.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logistics_invoices', to='orders.order')),
            ],
            options={
                'db_table': 'logistics_invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LogisticsInvoiceItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('packages_description', models.TextField(blank=True, help_text='No. & Kind of Packages')),
                ('description_of_goods', models.TextField(blank=True, help_text='Total N CODE etc.')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unit', models.CharField(default='Kg', max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_usd', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('amount_inr', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('li', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.logisticsinvoice')),
            ],
            options={
                'db_table': 'logistics_invoice_items',
            },
        ),
    ]
