# Generated by Django 6.0.3 on 2026-04-10 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_pi_version_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proformainvoiceitem',
            name='client_product_name',
            field=models.TextField(blank=True, default='', help_text='Product name as the client calls it'),
        ),
        migrations.AlterField(
            model_name='proformainvoiceitem',
            name='product_name',
            field=models.TextField(help_text='Company/internal product name'),
        ),
        migrations.AlterField(
            model_name='proformainvoiceitem',
            name='unit',
            field=models.TextField(blank=True, default='Ltrs'),
        ),
    ]
