# Generated by Django 6.0.3 on 2026-04-15 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_pi_item_text_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialinvoice',
            name='batch_no',
            field=models.CharField(blank=True, help_text='Batch/Lot number for the shipment', max_length=100),
        ),
    ]
