# Generated by Django 6.0.3 on 2026-04-24 06:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_add_client_tier'),
        ('finance', '0013_add_ci_batch_no'),
        ('orders', '0012_alter_orderdocument_doc_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PackingInstructionForm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('pif_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('po_no', models.CharField(blank=True, default='', max_length=100)),
                ('pif_date', models.DateField(blank=True, null=True)),
                ('product_name', models.CharField(blank=True, default='', max_length=255)),
                ('product_description', models.CharField(blank=True, default='', max_length=500)),
                ('packing_description', models.CharField(blank=True, default='', max_length=500)),
                ('quantity', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('container_left', models.JSONField(blank=True, default=dict)),
                ('container_right', models.JSONField(blank=True, default=dict)),
                ('packing_sections', models.JSONField(blank=True, default=list)),
                ('footer_note', models.TextField(blank=True, default='')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='pif/%Y/%m/')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pifs', to='clients.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pifs', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pifs', to='orders.order')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pifs', to='orders.orderitem')),
            ],
            options={
                'db_table': 'packing_instruction_forms',
                'ordering': ['-created_at'],
            },
        ),
    ]
