# Generated by Django 6.0.3 on 2026-04-24 10:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_add_client_tier'),
        ('finance', '0014_packinginstructionform'),
        ('orders', '0015_alter_orderdocument_doc_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PackingList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('list_type', models.CharField(choices=[('client', 'Client Packing List'), ('logistic', 'Logistic Packing List')], max_length=20)),
                ('invoice_number', models.CharField(db_index=True, max_length=50)),
                ('date', models.DateField(blank=True, null=True)),
                ('exporter_details', models.JSONField(blank=True, default=dict)),
                ('consignee_details', models.JSONField(blank=True, default=dict)),
                ('consignee_to', models.CharField(blank=True, default='', max_length=255)),
                ('notify_details', models.JSONField(blank=True, default=dict)),
                ('shipment_details', models.JSONField(blank=True, default=dict)),
                ('items', models.JSONField(blank=True, default=list)),
                ('container_details', models.CharField(blank=True, default='', max_length=255)),
                ('weight_summary', models.JSONField(blank=True, default=dict)),
                ('loading_details', models.JSONField(blank=True, default=list)),
                ('declaration', models.TextField(blank=True, default='')),
                ('grand_total', models.CharField(blank=True, default='', max_length=100)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='packing_lists/%Y/%m/')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing_lists', to='clients.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_packing_lists', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing_lists', to='orders.order')),
            ],
            options={
                'db_table': 'packing_lists',
                'ordering': ['-created_at'],
                'unique_together': {('order', 'list_type')},
            },
        ),
    ]
