# Generated by Django 6.0.3 on 2026-04-24 10:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_add_client_tier'),
        ('finance', '0015_packinglist'),
        ('orders', '0015_alter_orderdocument_doc_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('doc_type', models.CharField(choices=[('dbk_declaration', 'DBK Declaration'), ('examination_report', 'Examination Report'), ('export_declaration', 'Export Declaration Form'), ('factory_stuffing', 'Factory Stuffing Annexure')], max_length=40)),
                ('fields', models.JSONField(blank=True, default=dict)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='compliance/%Y/%m/')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_docs', to='clients.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_compliance_docs', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_docs', to='orders.order')),
            ],
            options={
                'db_table': 'compliance_documents',
                'ordering': ['-created_at'],
                'unique_together': {('order', 'doc_type')},
            },
        ),
    ]
