# Generated by Django 6.0.3 on 2026-04-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_compliancedocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliancedocument',
            name='doc_type',
            field=models.CharField(choices=[('dbk_declaration', 'DBK Declaration'), ('examination_report', 'Examination Report'), ('export_declaration', 'Export Declaration Form'), ('factory_stuffing', 'Factory Stuffing Annexure'), ('non_dg_declaration', 'Non-DG Declaration Letter')], max_length=40),
        ),
    ]
