# Generated by Django 6.0.3 on 2026-03-26 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_shadow_executive'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='tax_number',
            field=models.CharField(blank=True, help_text='GSTIN / CNPJ / VAT etc.', max_length=100),
        ),
    ]
