# Generated by Django 6.0.3 on 2026-04-11 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_protect_user_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='tier',
            field=models.CharField(choices=[('tier_1', 'Tier 1 - VIP'), ('tier_2', 'Tier 2 - Priority'), ('tier_3', 'Tier 3 - Standard')], db_index=True, default='tier_3', help_text='Client priority tier — Tier 1 (VIP) gets fastest follow-ups and special alerts', max_length=10),
        ),
    ]
