# Generated by Django 6.0.3 on 2026-03-21 11:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipment_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('packed', 'Packed'), ('dispatched', 'Dispatched'), ('in_transit', 'In Transit'), ('delivered', 'Delivered')], default='pending', max_length=20)),
                ('container_number', models.CharField(blank=True, max_length=50)),
                ('bl_number', models.CharField(blank=True, max_length=50)),
                ('forwarder', models.CharField(blank=True, max_length=255)),
                ('port_of_loading', models.CharField(blank=True, max_length=255)),
                ('port_of_discharge', models.CharField(blank=True, max_length=255)),
                ('delivery_terms', models.CharField(blank=True, max_length=20)),
                ('dispatch_date', models.DateField(blank=True, null=True)),
                ('transit_days', models.IntegerField(blank=True, null=True)),
                ('estimated_arrival', models.DateField(blank=True, null=True)),
                ('actual_arrival', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='clients.client')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='orders.order')),
            ],
            options={
                'db_table': 'shipments',
                'ordering': ['-created_at'],
            },
        ),
    ]
