# Generated by Django 6.0.3 on 2026-03-25 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='container_booking_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='factory_ready_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='freight_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='shipment',
            name='inspection_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipping_line',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='shipment',
            name='vessel_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='bl_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Bill of Lading'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('factory_ready', 'Factory Ready'), ('container_booked', 'Container Booked'), ('packed', 'Packed'), ('inspection', 'Under Inspection'), ('inspection_passed', 'Inspection Passed'), ('dispatched', 'Dispatched'), ('in_transit', 'In Transit'), ('arrived', 'Arrived at Port'), ('customs', 'Customs Clearance'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
    ]
