# Generated by Django 6.0.3 on 2026-03-25 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0002_shipment_container_booking_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
