# Generated by Django 6.0.3 on 2026-04-25 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0003_shipment_deleted_at_shipment_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='cha',
            field=models.CharField(blank=True, help_text='Customs House Agent', max_length=255),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='forwarder',
            field=models.CharField(blank=True, help_text='Freight Forwarder', max_length=255),
        ),
    ]
