# Generated by Django 6.0.3 on 2026-04-28 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0004_shipment_cha_alter_shipment_forwarder'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='country',
            field=models.CharField(blank=True, help_text="Destination country, populated from the client's country.", max_length=100),
        ),
    ]
